# ---------------------------------------------------------------------------- #
#                                   General                                    #
# ---------------------------------------------------------------------------- #

name = "hugo-legrec"
license = 'GNU GPL'
licenselink = 'https://github.com/legrec14/hugo-legrec/blob/main/LICENSE'
description = 'This is a theme created by legrec14 to fit its own needs.'

homepage = 'https://github.com/legrec14/hugo-legrec'

demosite = "https://github/legrec14.github.io/"

[author]
  name = "Guillaume Cugnet"
  homepage = "https://github.com/legrec14/hugo-legrec"

# ---------------------------------------------------------------------------- #
#                               Taxonomy terms                                 #
# ---------------------------------------------------------------------------- #

tags = ["blog"]
features = []
